[package]
name = "wp-editor"
version = "1.19.9"
edition = "2024"
build = "build.rs"


[build-dependencies]
serde_json = "1.0"


[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-web = "4.12"
actix-web-prom = "0.10"

tracing = "0.1"
simple-log = "2.4"


tokio = { version = "1.48", features = ["full"] }

rust-embed = "8.9"


mime_guess = "2"
config = "0.14"
toml = "0.9"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2.0"

regex = "1.12"
base64 = "0.22"
orion-error = "0.8"
tempfile = "3.24"
tree-sitter = "0.26"
tree-sitter-wpl = { package = "tree-sitter-wpl", git = "https://github.com/wp-labs/tree-sitter-wpl.git", branch = "main" }

# PostgreSQL 数据库支持 - SeaORM
sea-orm = { version = "2.0", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "with-chrono",
] }# --- External: Open API (Public Interfaces) ---

#wp-parse-api     =  "0.8"
wp-model-core    =  "0.8"

# --- External: Infrastructure Libraries ---

wp-error     =  "0.10"
wp-specs     =  "0.10"

wp-data-fmt  =  "0.2"
wp-editor-migrations = { path = "crates/migrations" }
wp-lang = "0.4"

wp_knowledge  = { package = "wp-knowledge",  version = "0.14"}

wp-engine     = {                            git = "https://github.com/wp-labs/wp-motor", tag = "v1.23.7" }

wp_oml         = { package = "wp-oml",       git = "https://github.com/wp-labs/wp-motor", tag = "v1.23.7" }
wp_data_utils = { package = "wp-data-utils", git = "https://github.com/wp-labs/wp-motor", tag = "v1.23.7" }


# wp-engine = { path = "../wp-motor" }
# wp-oml    = { package = "wp-oml",    path = "../wp-motor/crates/wp-oml" }
# wp-data-utils = { path = "../wp-motor/crates/wp-data-utils"  }

# wp-lang = {path = "../wp-lang"}
# wp-knowledge  = { path = "../wp-motor/crates/wp-knowledge" }
##wp-cli-core   = { path = "../wp-motor/crates/wp-cli-core" }

semver = "1.0.27"
