[package]
name = "wp-editor"
version = "1.18.0"
edition = "2024"
build = "build.rs"


[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-web = "4.12"
actix-web-prom = "0.10"
actix-files = "0.6"
tracing = "0.1"
simple-log = "2.4"
small_ctor = "0.1"
cargo_metadata = "0.20"
tokio = { version = "1.48", features = ["full"] }
tokio-util = "=0.7.10"
rust-embed = "8.9"
zip = "0.6"
zip-extract = "0.1"
actix-multipart = "0.7"
futures-util = "0.3"
mime_guess = "2"
config = "0.14"
toml = "0.9"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2.0"
strum = { version = "0.26", features = ["derive"] }
regex = "1.12"
base64 = "0.22"
orion-error = "0.6"
tempfile = "3.24"
tree-sitter = "0.26.6"
tree-sitter-wpl = { package = "tree-sitter-wpl", git = "https://github.com/wp-labs/tree-sitter-wpl.git", branch = "main" }

# PostgreSQL 数据库支持 - SeaORM
sea-orm = { version = "1.1", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "with-chrono",
] }# --- External: Open API (Public Interfaces) ---

wp-connector-api =  "0.8"
#wp-parse-api     =  "0.8"
wp-model-core    =  "0.8"

# --- External: Infrastructure Libraries ---
wp-log       =  "0.2"
wp-error     =  "0.8"
wp-specs     =  "0.8"
wp-conf-base =  "0.2"
wp-data-fmt  =  "0.2"
wp-editor-migrations = { path = "crates/migrations" }
wp-lang = "0.1"
wp_knowledge  = { package = "wp-knowledge",  version = "0.11"}

wp-engine     = {                            git = "https://github.com/wp-labs/wp-motor", tag = "v1.20.7" }
wp-config     = { package = "wp-config",     git = "https://github.com/wp-labs/wp-motor", tag = "v1.20.7" }
wp_oml         = { package = "wp-oml",       git = "https://github.com/wp-labs/wp-motor", tag = "v1.20.7" }
wp_data_utils = { package = "wp-data-utils", git = "https://github.com/wp-labs/wp-motor", tag = "v1.20.7" }
wp-proj       = { package = "wp-proj",       git = "https://github.com/wp-labs/wp-motor", tag = "v1.21.7" }

#wp-engine = { path = "../wp-motor" }
#wp-config = { path = "../wp-motor/crates/wp-config" }
#wp-oml    = { package = "wp-oml",    path = "../wp-motor/crates/wp-oml" }
#wp-lang   = { package = "wp-lang", path = "../wp-motor/crates/wp-lang" }
#wp-knowledge  = { path = "../wp-motor/crates/wp-knowledge" }
##wp-cli-core   = { path = "../wp-motor/crates/wp-cli-core" }
#wp-data-utils = { path = "../wp-motor/crates/wp-data-utils"  }
#wp-proj       = { path = "../wp-motor/crates/wp-proj" }


semver = "1.0.27"
