apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wp-editor.fullname" . }}
  labels:
    {{- include "wp-editor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wp-editor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or (not .Values.config.existingConfigMap) (not .Values.rules.existingConfigMap) .Values.podAnnotations }}
      annotations:
        {{- if not .Values.config.existingConfigMap }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if not .Values.rules.existingConfigMap }}
        checksum/rules: {{ include (print $.Template.BasePath "/rules-configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "wp-editor.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wp-editor.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.config.mountPath }}
              subPath: {{ .Values.config.subPath }}
              readOnly: true
            - name: rules
              mountPath: {{ .Values.rules.mountPath }}
              readOnly: true
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ default (printf "%s-config" (include "wp-editor.fullname" .)) .Values.config.existingConfigMap }}
        - name: rules
          configMap:
            name: {{ default (printf "%s-rules" (include "wp-editor.fullname" .)) .Values.rules.existingConfigMap }}
            {{- if not .Values.rules.existingConfigMap }}
            items:
              {{- range $path, $_ := .Files.Glob "wp-rule/models/**" }}
              - key: {{ trimPrefix "wp-rule/models/" $path | replace "/" "__" }}
                path: {{ trimPrefix "wp-rule/models/" $path }}
              {{- end }}
            {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
